name: CI_Docker
on:
  push:
    branches: ["main"]

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: CheckOut code
        uses: actions/checkout@v4
      - name: Log in GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository}}:latest

